name: Update news every 3 hours

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push updated news
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add news.json
          git commit -m 'Auto-update news' || echo "No changes to commit"
          git push
